-- Catch-up migration for environments that only have initial tables.
-- Safe to run multiple times.

-- -----------------------------
-- movie_followers
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.movie_followers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT movie_followers_user_movie_unique UNIQUE (user_id, movie_id)
);

CREATE INDEX IF NOT EXISTS idx_movie_followers_user_id
  ON public.movie_followers (user_id);
CREATE INDEX IF NOT EXISTS idx_movie_followers_movie_id
  ON public.movie_followers (movie_id);

ALTER TABLE public.movie_followers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'movie_followers' AND policyname = 'movie_followers_select_own'
  ) THEN
    CREATE POLICY movie_followers_select_own
      ON public.movie_followers FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'movie_followers' AND policyname = 'movie_followers_insert_own'
  ) THEN
    CREATE POLICY movie_followers_insert_own
      ON public.movie_followers FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'movie_followers' AND policyname = 'movie_followers_delete_own'
  ) THEN
    CREATE POLICY movie_followers_delete_own
      ON public.movie_followers FOR DELETE
      USING (auth.uid() = user_id);
  END IF;
END
$$;

-- -----------------------------
-- notifications
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  movie_id TEXT NOT NULL,
  type TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  event_key TEXT
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
  ON public.notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_movie_id
  ON public.notifications (movie_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id_is_read
  ON public.notifications (user_id, is_read);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_user_event_key_unique
  ON public.notifications (user_id, event_key)
  WHERE event_key IS NOT NULL;

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'notifications' AND policyname = 'notifications_select_own'
  ) THEN
    CREATE POLICY notifications_select_own
      ON public.notifications FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'notifications' AND policyname = 'notifications_update_own'
  ) THEN
    CREATE POLICY notifications_update_own
      ON public.notifications FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'notifications' AND policyname = 'notifications_delete_own'
  ) THEN
    CREATE POLICY notifications_delete_own
      ON public.notifications FOR DELETE
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'notifications' AND policyname = 'notifications_insert_service_role'
  ) THEN
    CREATE POLICY notifications_insert_service_role
      ON public.notifications FOR INSERT
      WITH CHECK (auth.uid() IS NULL);
  END IF;
END
$$;

-- -----------------------------
-- followed_title_state
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.followed_title_state (
  movie_id TEXT PRIMARY KEY,
  media_type TEXT NOT NULL,
  tmdb_id INTEGER NOT NULL,
  release_date DATE,
  status TEXT,
  number_of_seasons INTEGER,
  last_episode_air_date DATE,
  last_episode_season_number INTEGER,
  last_episode_number INTEGER,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_followed_title_state_media_type
  ON public.followed_title_state (media_type);

-- -----------------------------
-- collections
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_collections_user_id
  ON public.collections (user_id);

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collections' AND policyname = 'collections_select_own'
  ) THEN
    CREATE POLICY collections_select_own
      ON public.collections FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collections' AND policyname = 'collections_insert_own'
  ) THEN
    CREATE POLICY collections_insert_own
      ON public.collections FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collections' AND policyname = 'collections_update_own'
  ) THEN
    CREATE POLICY collections_update_own
      ON public.collections FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collections' AND policyname = 'collections_delete_own'
  ) THEN
    CREATE POLICY collections_delete_own
      ON public.collections FOR DELETE
      USING (auth.uid() = user_id);
  END IF;
END
$$;

-- -----------------------------
-- collection_items
-- -----------------------------
CREATE TABLE IF NOT EXISTS public.collection_items (
  collection_id BIGINT NOT NULL REFERENCES public.collections(id) ON DELETE CASCADE,
  media_id BIGINT NOT NULL,
  media_type TEXT NOT NULL CHECK (media_type IN ('movie', 'tv')),
  added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (collection_id, media_id, media_type)
);

CREATE INDEX IF NOT EXISTS idx_collection_items_collection_id
  ON public.collection_items (collection_id);

ALTER TABLE public.collection_items ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collection_items' AND policyname = 'collection_items_select_own'
  ) THEN
    CREATE POLICY collection_items_select_own
      ON public.collection_items FOR SELECT
      USING (
        EXISTS (
          SELECT 1
          FROM public.collections c
          WHERE c.id = collection_id
            AND c.user_id = auth.uid()
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collection_items' AND policyname = 'collection_items_insert_own'
  ) THEN
    CREATE POLICY collection_items_insert_own
      ON public.collection_items FOR INSERT
      WITH CHECK (
        EXISTS (
          SELECT 1
          FROM public.collections c
          WHERE c.id = collection_id
            AND c.user_id = auth.uid()
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'collection_items' AND policyname = 'collection_items_delete_own'
  ) THEN
    CREATE POLICY collection_items_delete_own
      ON public.collection_items FOR DELETE
      USING (
        EXISTS (
          SELECT 1
          FROM public.collections c
          WHERE c.id = collection_id
            AND c.user_id = auth.uid()
        )
      );
  END IF;
END
$$;
